version: '3.8'

services:
  mlb-show-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlbtheshow-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy-network
    volumes:
      - db-data:/app/data

  mlb-show-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: mlbtheshow-worker
    restart: unless-stopped
    command: node worker.mjs
    networks:
      - proxy-network
    volumes:
      - db-data:/app/data
      
networks:
  proxy-network:
    external: true

volumes:
  db-data:
